export default {
  header: 'Предложения',
  about: 'подробней',
  stats: 'статистика',
  description: 'Описание',
  rules: 'Правила',
  programs: 'Программы',
  new: 'Новая программа',
  save: 'сохранить',
  phone: 'Телефон',
  wallet: 'Кошелёк',
  leads: 'Лиды',
  filter: {
    categories: {
      label: 'Категории',
      realEstate: 'Недвижимость',
      insuranceAndLoans: 'Страхование и кредиты',
      eCommerce: 'Электронная коммерция',
      tourism: 'Туризм',
      legalServices: 'Юридические услуги',
      cars: 'Машины',
      constructionAndRenovation: 'Строительство и ремонт',
      medicine: 'Медицина',
      other: 'Другое'
    },
    promotionTypes: {
      label: 'Реклама',
      online: 'онлайн',
      offline: 'оффлайн',
      mobile: 'мобильный'
    },
    trafficTypes: {
      label: 'Трафик',
      onlineSearch: 'Online поисковый',
      onlineCPC: 'Online CPC',
      onlineBanners: '​Online баннерный​​',
      onlineXML: '​Online XML (классифайд/товарные фиды)​​',
      onlineSMM: '​Online SMM',
      onlineMotivate: '​Online мотивированный​​',
      onlineSoftware: '​Online ПО (тул бары, дорвеи)',
      onlineByBrand: '​Online трафик на бренд​​',
      onlineCoupon: '​Online купонный​​',
      onlineEmail: '​Online емейл​​',
      onlineContent: '​Online контент (статьи, блоги)​​',
      onlineRetarget: '​Online ретаргетинг​​',
      onlineAds: 'Online доски объявлений',
      mobileSoftware: '​Мобильный приложения​​',
      mobileBanners: '​Мобильный баннерный​​',
      mobileCPC: '​Мобильный CPC',
      mobileSearch: '​Мобильный поисковый​​',
      mobileSMS: '​Мобильный SMS',
      mobileMessengers: '​Мобильный Messengers (Whatsapp, Telegram, Viber, iMessage)​​',
      mobileOther: '​Мобильный прочее​​',
      offlineOutdoor: '​Оффлайн наружная реклама​​',
      offlineRadio: '​Оффлайн радио​​',
      offlineTV: '​Оффлайн ТВ',
      offlineCalls: '​Оффлайн коллцентр​​',
      offlinePrints: '​Оффлайн печатные издания​​',
      offlineMails: '​Оффлайн почтовые рассылки​​',
      offlineOther: '​Оффлайн прочее​​'
    },
    promoTools: {
      label: 'Материалы',
      banners: 'Банер',
      landingPages: 'Лендинг',
      xmlFeeds: 'XML фид',
      tgb: 'TGB',
      printingMaterials: 'Печатные материалы',
      emailTemplates: 'E-mail шаблоны',
      keywords: 'Ключевые слова',
      websites: 'Сайты',
      videos: 'Видео'
    },
    enrollment: {
      label: 'Регистрация',
      all: 'Все',
      enrollment: 'Зарегистрированные',
      notEnrolled: 'Не зарегестрированные'
    }
  }
}
