export default {
  header: 'Dashboard',
  totalLeads: 'Total Leads',
  soldLeads: 'Sold Leads',
  conversion: 'Conversion',
  earnedHQX: 'Earn, HQX',
  earnedSpent: 'Earned & Spent',
  earned: 'Earned',
  spent: 'Spent',
  cr: 'CR',
  recentStats: 'Recent Stats',
  date: 'Date',
  view: 'View',
  accountBalance: 'Account Balance',
  total: 'Total',
  wallet: 'Wallet',
  history: 'History',
  myNetworks: 'My Networks',
  activeNetwork: 'Active Network',
  refusedCalls: 'Refused Calls',
  program: 'Program',
  duration: 'Duration',
  state: 'State',
  actions: 'Actions',
  seeAllRefused: 'See All Refused Calls',
  myManager: 'My Manager',
  sendAMessage: 'Send A Message',
  activePrograms: 'Active Programs',
  title: 'Title',
  month: 'Month',
  week: 'Week',
  today: 'Today',
  allPrograms: 'All Programs',
  myTickets: 'My Tickets',
  noTickets: 'Currently no open tickets',
  recentOffers: 'Recent Offers',
  noNewOffers: 'No new offers',
  allOffers: 'All Offers',
  payoutRequests: 'Payout Requests',
  noPayoutRequests: 'Currently no payout requests',
  news: 'News',
  referralProgram: 'Referral Program',
  yourPercentage: 'Your Percentage',
  totalReferrals: 'Total Referrals',
  earnedPerMonth: 'Earned (per month)'
}
