export default {
  header: 'Отчеты',
  totalLeads: 'Всего лидов',
  soldLeads: 'Продано лидов',
  conversion: 'Коэффициент',
  earnedHQX: 'Заработано HQX',
  earnedSpent: 'Заработано и потрачено',
  earned: 'Заработано',
  spent: 'Потрачено',
  cr: 'Коэффициент',
  recentStats: 'Статистика',
  date: 'Дата',
  view: 'Просмотреть',
  accountBalance: 'Баланс аккаунта',
  total: 'Всего',
  wallet: 'Кошелёк',
  history: 'История',
  myNetworks: 'Мои сети',
  activeNetwork: 'Текущая сеть',
  refusedCalls: 'Отказанные звонки',
  program: 'Программа',
  duration: 'Длительность',
  state: 'Состояние',
  actions: 'Действия',
  seeAllRefused: 'Просмотреть все отказанные звонки',
  myManager: 'Мой менеджер',
  sendAMessage: 'Написать сообщение',
  activePrograms: 'Активные программы',
  title: 'Название',
  month: 'Месяц',
  week: 'Неделя',
  today: 'Сегодня',
  allPrograms: 'Все программы',
  myTickets: 'Мои запросы',
  noTickets: 'Нет открытых запросов',
  recentOffers: 'Предложения',
  noNewOffers: 'Нет новых предложений',
  allOffers: 'Все предложения',
  payoutRequests: 'Запросы выплат',
  noPayoutRequests: 'Нет запросов выплат',
  news: 'Новости',
  referralProgram: 'Реферралы',
  yourPercentage: 'Ваш процент',
  totalReferrals: 'Всего реферралов',
  earnedPerMonth: 'Заработано за месяц'
}
